#!/bin/bash

# Export environment variables
export CC="/c/Program Files (x86)/Intel/oneAPI/compiler/2024.2/bin/icx.exe"
export CXX="/c/Program Files (x86)/Intel/oneAPI/compiler/2024.2/bin/icpx.exe"
export CI=true
export CMAKE_PREFIX_PATH="/c/Program Files (x86)/Intel/oneAPI/tbb/latest/env:/c/Program Files (x86)/Intel/oneAPI/dpl/latest/lib/cmake/oneDPL:/c/Program Files (x86)/Intel/oneAPI/compiler/latest"
export CMPLR_ROOT="/c/Program Files (x86)/Intel/oneAPI/compiler/latest"
export COBERTURA_HOME="/c/cobertura-2.1.1"
export CommandPromptType=Native
export CommonProgramFiles="/c/Program Files/Common Files"
export CONDA="/c/Miniconda"
export CPATH="/c/Program Files (x86)/Intel/oneAPI/tbb/latest/include:/c/Program Files (x86)/Intel/oneAPI/ocloc/latest/include:/c/Program Files (x86)/Intel/oneAPI/dpl/latest/include:/c/Program Files (x86)/Intel/oneAPI/dev-utilities/latest/include:/c/Program Files (x86)/Intel/oneAPI/compiler/latest/include"
export DEPLOYMENT_BASEPATH="/c/actions"
export DevEnvDir="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE"
export DIAGUTIL_PATH="/c/Program Files (x86)/Intel/oneAPI/debugger/latest/etc/debugger/sys_check"
export DOTNET_MULTILEVEL_LOOKUP=0
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
export DPL_ROOT="/c/Program Files (x86)/Intel/oneAPI/dpl/latest"
export DriverData="/c/Windows/System32/Drivers/DriverData"
export EdgeWebDriver="/c/SeleniumWebDrivers/EdgeDriver"
export ExtensionSdkDir="/c/Program Files (x86)/Microsoft SDKs/Windows Kits/10/ExtensionSDKs"
export Framework40Version=v4.0
export FrameworkDir="/c/Windows/Microsoft.NET/Framework64"
export FrameworkDIR64="/c/Windows/Microsoft.NET/Framework64"
export FrameworkVersion=v4.0.30319
export FrameworkVersion64=v4.0.30319
export FSHARPINSTALLDIR="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools"
export GCM_INTERACTIVE=Never
export HOMEPATH="\Users\runneradmin"
export HTMLHelpDir="/c/Program Files (x86)/HTML Help Workshop"
export IEWebDriver="/c/SeleniumWebDrivers/IEDriver"
export IFCPATH="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/ifc/x64"
export ImageOS=win19
export ImageVersion=20250511.1.0
export INCLUDE="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/ATLMFC/include:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/include:/c/Program Files (x86)/Windows Kits/NETFXSDK/4.8/include/um:/c/Program Files (x86)/Windows Kits/10/include/10.0.22621.0/ucrt:/c/Program Files (x86)/Windows Kits/10/include/10.0.22621.0/shared:/c/Program Files (x86)/Windows Kits/10/include/10.0.22621.0/um:/c/Program Files (x86)/Windows Kits/10/include/10.0.22621.0/winrt:/c/Program Files (x86)/Windows Kits/10/include/10.0.22621.0/cppwinrt:/c/Program Files (x86)/Intel/oneAPI/tbb/latest/include:/c/Program Files (x86)/Intel/oneAPI/ocloc/latest/include:/c/Program Files (x86)/Intel/oneAPI/dev-utilities/latest/include:/c/Program Files (x86)/Intel/oneAPI/compiler/latest/include"
export INSTALL_DIR="D:/a/unified-memory-framework/unified-memory-framework/build/install"
export INTELGTDEBUGGERROOT="/c/Program Files (x86)/Intel/oneAPI/debugger/latest/env"
export JAVA_HOME="/c/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.452-9/x64"
export JAVA_HOME_8_X64="/c/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.452-9/x64"
export LIB="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/ATLMFC/lib/x64:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/lib/x64:/c/Program Files (x86)/Windows Kits/NETFXSDK/4.8/lib/um/x64:/c/Program Files (x86)/Windows Kits/10/lib/10.0.22621.0/ucrt/x64:/c/Program Files (x86)/Windows Kits/10/lib/10.0.22621.0/um/x64:/c/Program Files (x86)/Intel/oneAPI/tbb/latest/lib:/c/Program Files (x86)/Intel/oneAPI/compiler/latest/lib/clang/18/lib/windows:/c/Program Files (x86)/Intel/oneAPI/compiler/latest/opt/compiler/lib:/c/Program Files (x86)/Intel/oneAPI/compiler/latest/lib"
export LIBPATH="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/ATLMFC/lib/x64:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/lib/x64:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/lib/x86/store/references:/c/Program Files (x86)/Windows Kits/10/UnionMetadata/10.0.22621.0:/c/Program Files (x86)/Windows Kits/10/References/10.0.22621.0:/c/Windows/Microsoft.NET/Framework64/v4.0.30319"
export LOCALAPPDATA="/c/Users/runneradmin/AppData/Local"
export MAVEN_OPTS=-Xms256m
export NETFXSDKDir="/c/Program Files (x86)/Windows Kits/NETFXSDK/4.8"
export npm_config_prefix="/c/npm/prefix"
export NUMBER_OF_PROCESSORS=4
export OCLOC_ROOT="/c/Program Files (x86)/Intel/oneAPI/ocloc/latest"
export OCL_ICD_FILENAMES="/c/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/intelocl64_emu.dll:/c/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/intelocl64.dll"
export ONEAPI_ROOT="/c/Program Files (x86)/Intel/oneAPI"
export OS=Windows_NT
export Path="/c/Program Files (x86)/Intel/oneAPI/compiler/2024.2/bin:/c/msys64/mingw64/bin:/c/msys64/usr/bin:/c/msys64/bin:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/VC/VCPackages:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/bin/Roslyn:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Team Tools/Performance Tools/x64:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Team Tools/Performance Tools:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/vs2019/x64:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/vs2019:/c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64:/c/Program Files (x86)/HTML Help Workshop:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/devinit:/c/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64:/c/Program Files (x86)/Windows Kits/10/bin/x64:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin:/c/Windows/Microsoft.NET/Framework64/v4.0.30319:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools:/c/Program Files (x86)/Intel/oneAPI/tbb/latest/bin:/c/Program Files (x86)/Intel/oneAPI/ocloc/latest/bin:/c/Program Files (x86)/Intel/oneAPI/dev-utilities/latest/bin:/c/Program Files (x86)/Intel/oneAPI/debugger/latest/opt/debugger/bin:/c/Program Files (x86)/Intel/oneAPI/compiler/latest/lib/ocloc:/c/Program Files (x86)/Intel/oneAPI/compiler/latest/bin:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/VC/VCPackages:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/bin/Roslyn:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Team Tools/Performance Tools/x64:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Team Tools/Performance Tools:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/vs2019/x64:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/vs2019:/c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64:/c/Program Files (x86)/HTML Help Workshop:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/devinit:/c/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64:/c/Program Files (x86)/Windows Kits/10/bin/x64:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin:/c/Windows/Microsoft.NET/Framework64/v4.0.30319:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools:/d/a/unified-memory-framework/unified-memory-framework/ninja-build:/d/a/unified-memory-framework/unified-memory-framework/build/vcpkg:/c/Program Files/MongoDB/Server/5.0/bin:/c/aliyun-cli:/c/vcpkg:/c/cf-cli:/c/Program Files (x86)/NSIS:/c/tools/zstd:/c/Program Files/Mercurial:/c/hostedtoolcache/windows/stack/3.5.1/x64:/c/cabal/bin:/c/ghcup/bin:/c/mingw64/bin:/c/Program Files/dotnet:/c/Program Files/MySQL/MySQL Server 5.7/bin:/c/Program Files/R/R-4.4.2/bin/x64:/c/SeleniumWebDrivers/GeckoDriver:/c/SeleniumWebDrivers/EdgeDriver:/c/SeleniumWebDrivers/ChromeDriver:/c/Program Files (x86)/sbt/bin:/c/Program Files (x86)/GitHub CLI:/c/Program Files/Git/bin:/c/Program Files (x86)/pipx_bin:/c/npm/prefix:/c/hostedtoolcache/windows/go/1.24.3/x64/bin:/c/hostedtoolcache/windows/Python/3.9.13/x64/Scripts:/c/hostedtoolcache/windows/Python/3.9.13/x64:/c/hostedtoolcache/windows/Ruby/3.0.7/x64/bin:/c/Program Files/OpenSSL/bin:/c/tools/kotlinc/bin:/c/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.452-9/x64/bin:/c/Program Files/ImageMagick-7.1.1-Q16-HDRI:/c/Program Files/Microsoft SDKs/Azure/CLI2/wbin:/c/ProgramData/kind:/c/Program Files/Eclipse Foundation/jdk-8.0.302.8-hotspot/bin:/c/ProgramData/Chocolatey/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/PowerShell/7:/c/Program Files/Microsoft/Web Platform Installer:/c/Program Files/TortoiseSVN/bin:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files (x86)/WiX Toolset v3.14/bin:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/160/DTS/Binn:/c/Strawberry/c/bin:/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/ProgramData/chocolatey/lib/pulumi/tools/Pulumi/bin:/c/Program Files/CMake/bin:/c/ProgramData/chocolatey/lib/maven/apache-maven-3.9.9/bin:/c/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code:/c/Program Files/Microsoft SDKs/Service Fabric/Tools/ServiceFabricLocalClusterManager:/c/Program Files/nodejs:/c/Program Files/Git/cmd:/c/Program Files/Git/mingw64/bin:/c/Program Files/Git/usr/bin:/c/Program Files/GitHub CLI:/c/tools/php:/c/Program Files (x86)/sbt/bin:/c/Program Files/Amazon/AWSCLIV2:/c/Program Files/Amazon/SessionManagerPlugin/bin:/c/Program Files/Amazon/AWSSAMCLI/bin:/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin:/c/Program Files (x86)/Microsoft BizTalk Server:/c/Program Files/LLVM/bin:/c/Users/runneradmin/.dotnet/tools:/c/Users/runneradmin/.cargo/bin:/c/Users/runneradmin/AppData/Local/Microsoft/WindowsApps:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/x64/bin:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/VC/Linux/bin/ConnectionManagerExe:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/x64/bin:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja:/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/VC/Linux/bin/ConnectionManagerExe"
export PATHEXT=".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
export PIPX_HOME="/c/Program Files (x86)/pipx"
export PKG_CONFIG_PATH="/c/Program Files (x86)/Intel/oneAPI/tbb/latest/lib/pkgconfig:/c/Program Files (x86)/Intel/oneAPI/dpl/latest/lib/pkgconfig:/c/Program Files (x86)/Intel/oneAPI/compiler/latest/lib/pkgconfig"
export Platform=x64
export POWERSHELL_DISTRIBUTION_CHANNEL=GitHub-Actions-win19
export SELENIUM_JAR_PATH="/c/selenium/selenium-server.jar"
export SETVARS_COMPLETED=1
export STATS_BLT=true
export SystemRoot="/c/Windows"
export TBBROOT="/c/Program Files (x86)/Intel/oneAPI/tbb/latest"
export TBB_BIN_DIR="/c/Program Files (x86)/Intel/oneAPI/tbb/latest/bin"
export TBB_DLL_PATH="/c/Program Files (x86)/Intel/oneAPI/tbb/latest/bin"
export TBB_SCRIPT_DIR="/c/Program Files (x86)/Intel/oneAPI/tbb/latest/env"
export TBB_TARGET_ARCH=intel64
export TEMP="/c/Users/RUNNER~1/AppData/Local/Temp"
export TMP="/c/Users/RUNNER~1/AppData/Local/Temp"
export UCRTVersion=10.0.22621.0
export UniversalCRTSdkDir="/c/Program Files (x86)/Windows Kits/10"
export USERDOMAIN=fv-az838-527
export USERPROFILE="/c/Users/runneradmin"
export USE_INTEL_LLVM=0
export VARSDIR="/c/Program Files (x86)/Intel/oneAPI/ocloc/latest/env"
export VCIDEInstallDir="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/VC"
export VCINSTALLDIR="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC"
export VCPKG_BINARY_SOURCES="clear;x-gha,readwrite"
export VCPKG_ROOT="D:/a/unified-memory-framework/unified-memory-framework/build/vcpkg"
export VS140COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/Tools"
export VS160COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools"
export VSCMD_ARG_app_plat=Desktop
export VSCMD_ARG_HOST_ARCH=x64
export VSCMD_ARG_TGT_ARCH=x64
export VSCMD_VER=16.11.46
export VSINSTALLDIR="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise"
export VSSDK150INSTALL="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VSSDK"
export VSSDKINSTALL="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VSSDK"
export windir="/c/Windows"
export WindowsLibPath="/c/Program Files (x86)/Windows Kits/10/UnionMetadata/10.0.22621.0:/c/Program Files (x86)/Windows Kits/10/References/10.0.22621.0"
export WindowsSdkBinPath="/c/Program Files (x86)/Windows Kits/10/bin"
export WindowsSdkDir="/c/Program Files (x86)/Windows Kits/10"
export WindowsSDKLibVersion="10.0.22621.0"
export WindowsSdkVerBinPath="/c/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0"
export WindowsSDKVersion="10.0.22621.0"
export WindowsSDK_ExecutablePath_x64="/c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64"
export WindowsSDK_ExecutablePath_x86="/c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools"
export WIX="/c/Program Files (x86)/WiX Toolset v3.14"
export __devinit_path="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/devinit/devinit.exe"
export __DOTNET_ADD_64BIT=1
export __DOTNET_PREFERRED_BITNESS=64
export __MS_VC_INSTALL_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133"
export __VSCMD_PREINIT_PATH="/d/a/unified-memory-framework/unified-memory-framework/ninja-build:/d/a/unified-memory-framework/unified-memory-framework/build/vcpkg:/c/Program Files/MongoDB/Server/5.0/bin:/c/aliyun-cli:/c/vcpkg:/c/cf-cli:/c/Program Files (x86)/NSIS:/c/tools/zstd:/c/Program Files/Mercurial:/c/hostedtoolcache/windows/stack/3.5.1/x64:/c/cabal/bin:/c/ghcup/bin:/c/mingw64/bin:/c/Program Files/dotnet:/c/Program Files/MySQL/MySQL Server 5.7/bin:/c/Program Files/R/R-4.4.2/bin/x64:/c/SeleniumWebDrivers/GeckoDriver:/c/SeleniumWebDrivers/EdgeDriver:/c/SeleniumWebDrivers/ChromeDriver:/c/Program Files (x86)/sbt/bin:/c/Program Files (x86)/GitHub CLI:/c/Program Files/Git/bin:/c/Program Files (x86)/pipx_bin:/c/npm/prefix:/c/hostedtoolcache/windows/go/1.24.3/x64/bin:/c/hostedtoolcache/windows/Python/3.9.13/x64/Scripts:/c/hostedtoolcache/windows/Python/3.9.13/x64:/c/hostedtoolcache/windows/Ruby/3.0.7/x64/bin:/c/Program Files/OpenSSL/bin:/c/tools/kotlinc/bin:/c/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.452-9/x64/bin:/c/Program Files/ImageMagick-7.1.1-Q16-HDRI:/c/Program Files/Microsoft SDKs/Azure/CLI2/wbin:/c/ProgramData/kind:/c/Program Files/Eclipse Foundation/jdk-8.0.302.8-hotspot/bin:/c/ProgramData/Chocolatey/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/PowerShell/7:/c/Program Files/Microsoft/Web Platform Installer:/c/Program Files/TortoiseSVN/bin:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files (x86)/WiX Toolset v3.14/bin:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/160/DTS/Binn:/c/Strawberry/c/bin:/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/ProgramData/chocolatey/lib/pulumi/tools/Pulumi/bin:/c/Program Files/CMake/bin:/c/ProgramData/chocolatey/lib/maven/apache-maven-3.9.9/bin:/c/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code:/c/Program Files/Microsoft SDKs/Service Fabric/Tools/ServiceFabricLocalClusterManager:/c/Program Files/nodejs:/c/Program Files/Git/cmd:/c/Program Files/Git/mingw64/bin:/c/Program Files/Git/usr/bin:/c/Program Files/GitHub CLI:/c/tools/php:/c/Program Files (x86)/sbt/bin:/c/Program Files/Amazon/AWSCLIV2:/c/Program Files/Amazon/SessionManagerPlugin/bin:/c/Program Files/Amazon/AWSSAMCLI/bin:/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin:/c/Program Files (x86)/Microsoft BizTalk Server:/c/Program Files/LLVM/bin:/c/Users/runneradmin/.dotnet/tools:/c/Users/runneradmin/.cargo/bin:/c/Users/runneradmin/AppData/Local/Microsoft/WindowsApps"
export __VSCMD_PREINIT_VCToolsVersion=14.29.30133
export __VSCMD_PREINIT_VS160COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools"
export __VSCMD_script_err_count=0
